export const FEISHU_AD_DAILY_FIELDS = {
  date: 'Date',
  accountId: 'Account ID',
  accountName: 'Account Name',
  campaignId: 'Campaign ID',
  campaignName: 'Campaign Name',
  adsetId: 'Ad Set ID',
  adsetName: 'Ad Set Name',
  adId: 'Ad ID',
  adName: 'Ad Name',
  creativeId: 'Creative ID',
  objective: '广告目标',
  optimizationGoal: 'Optimization Goal',
  spend: 'Spend',
  impressions: 'Impressions',
  reach: 'Reach',
  frequency: 'Frequency',
  clicks: 'Clicks',
  linkClicks: 'Link Clicks',
  outboundClicks: 'Outbound Clicks',
  ctr: 'CTR',
  cpc: 'CPC',
  cpm: 'CPM',
  landingPageView: 'Landing Page View',
  addToCart: 'Add To Cart',
  initiateCheckout: 'Initiate Checkout',
  purchase: 'Purchase',
  purchaseValue: 'Purchase Value',
  roas: 'ROAS',
  cpa: '单次成效成本',
  cpaFallback: 'Cost per Purchase',
  attributionSetting: 'Attribution Setting',
  actionReportTime: 'Action Report Time',
  syncTime: 'Sync Time',
  lastRefreshedAt: 'Last Refreshed At',
} as const;

export const FEISHU_CREATIVE_FIELDS = {
  creativeId: 'Creative ID',
  assetGroupKey: 'Asset Group Key',
  adId: 'Ad ID',
  adName: 'Ad Name',
  campaignId: 'Campaign ID',
  adsetId: 'Ad Set ID',
  creativeName: 'Creative Name',
  creativeType: 'Creative Type',
  creativeTypeCn: '素材类型',
  videoId: 'Video ID',
  videoUrl: 'Video URL',
  originalVideoFileUrl: 'Original Video File URL',
  originalImageFileUrl: 'Original Image File URL',
  originalAssetAttachment: 'Original Asset Attachment',
  assetSource: 'Asset Source',
  manualAssetNote: 'Manual Asset Note',
  thumbnailUrl: 'Thumbnail URL',
  imageUrl: 'Image URL',
  primaryText: 'Primary Text',
  headline: 'Headline',
  description: 'Description',
  cta: 'CTA',
  landingPageUrl: 'Landing Page URL',
  product: 'Product',
  productCn: '产品',
  audience: '受众',
  materialDirection: '素材方向',
  materialName: '素材名',
  materialType: '素材类型',
  materialBatch: '素材批次',
  effectiveStatus: 'Effective Status',
  configuredStatus: 'Configured Status',
  adCreatedTime: 'Ad Created Time',
  adUpdatedTime: 'Ad Updated Time',
  aiAnalysisStatus: 'AI Analysis Status',
  lastSyncedAt: 'Last Synced At',
} as const;

export const FEISHU_RELATION_FIELDS = {
  uniqueKey: 'Unique Key',
  adId: 'Ad ID',
  adName: 'Ad Name',
  campaignId: 'Campaign ID',
  campaignName: 'Campaign Name',
  adsetId: 'Ad Set ID',
  adsetName: 'Ad Set Name',
  creativeId: 'Creative ID',
  creativeName: 'Creative Name',
  effectiveStatus: 'Effective Status',
  configuredStatus: 'Configured Status',
  product: 'Product',
  audience: 'Audience',
  firstSeenAt: 'First Seen At',
  lastSeenAt: 'Last Seen At',
  lastSyncedAt: 'Last Synced At',
} as const;

export const FEISHU_AI_ANALYSIS_FIELDS = {
  creativeId: 'Creative ID',
  videoType: 'Video Type',
  hookType: 'Hook Type',
  first3sDescription: 'First 3s Description',
  hasHuman: 'Has Human',
  hasVoiceover: 'Has Voiceover',
  hasSubtitles: 'Has Subtitles',
  productFirstAppearSecond: 'Product First Appear Second',
  mainSellingPoints: 'Main Selling Points',
  scriptStructure: 'Script Structure',
  aiSummary: 'AI Summary',
  aiConfidence: 'AI Confidence',
} as const;

export const FEISHU_RECOMMENDATION_FIELDS = {
  id: 'ID',
  date: 'Date',
  recommendationType: 'Recommendation Type',
  objectType: 'Object Type',
  objectId: 'Object ID',
  objectName: 'Object Name',
  priority: 'Priority',
  problemDescription: 'Problem Description',
  keyMetrics: 'Key Metrics',
  suggestedAction: 'Suggested Action',
  reasoningSummary: 'Reasoning Summary',
  confidence: 'Confidence',
  status: 'Status',
  generatedAt: 'Generated At',
} as const;

function uniqueFieldNames(fields: Record<string, string>): string[] {
  return Array.from(new Set(Object.values(fields)));
}

export const FEISHU_TABLE_FIELD_NAMES = {
  adDaily: uniqueFieldNames(FEISHU_AD_DAILY_FIELDS),
  creatives: uniqueFieldNames(FEISHU_CREATIVE_FIELDS),
  relations: uniqueFieldNames(FEISHU_RELATION_FIELDS),
  aiAnalysis: uniqueFieldNames(FEISHU_AI_ANALYSIS_FIELDS),
  recommendations: uniqueFieldNames(FEISHU_RECOMMENDATION_FIELDS),
} as const;
